### ISSUE TITLE
Freeze and quit

### ISSUE THREAD

**Issue by GeorgeTurner** [slightlydiff/Look-Out-For-Me-Public#32]
App is randomly freezing and quitting when using push notification alerts. Often problem associated with not having app open at all as has been closed but timer and alerts continued. 
![image](https://cloud.githubusercontent.com/assets/14720428/10630160/5b753618-7831-11e5-881f-8dfc17158910.png)

**Comment by slightlydiff** [comment]
I've not managed to replicate this issue on my iPhone or iPad but can see where it might be occurring in the code although it's certainly not expected behaviour.

I have therefore used extra coding to check the switch element is not null and is initiated before making the call that causes this issue.

I'll close the ticket but re-open it if you still have the issue on testing
